### ISSUE TITLE
Failure on launching BOSS device when using BEST toolbox

### ISSUE THREAD

**Issue by messhiroZZ** [umair-hassan/best-toolbox#50]
Hi Umair,

We are doing our sleeping spindle-based TMS-EEG in Tubingen. We are trying to replicate all the settings from our collaborators in Mainz (Prof. Bergmann), including the old black BOSS device and Matlab 2017b. But I failed to launch the boss device using script b = bossdevice; it says Target tg needs to be running. I printed out the tg it shows Mode = Target not ready due to a model initialization error. When I used my colleagues' firmware, it worked normally. I think it might be the DBSP.mldatx because it could be customized for spindle detection, I guess? And I even cannot open or edit it via Simulink. Do you have any good ideas for this?

Best

**Comment by messhiroZZ** [comment]
And by the way, Jiahua created a group for us. You may have a review of the bug report pics there.

**Comment by umair-hassan** [comment]
Hello Messhiro,

Thanks for letting me know - The .mldatx file can't be opened in simulink since it is copyright protected. 

Could you share the mac address of the computer connected to the bossdevice so that I can enable it for the spindle firmware - which is usually fine but sometimes firewalls needs to be unrestricted. 

Best,
Umair
